import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'build',
      'dist',
      'coverage',
      'node_modules',
      '**/node_modules/**',
      'scripts',
      'tests/load',
      'mobile',
      'mobile/**',
      'supabase/functions',
       'e2e',
       'service.ts',
       'docs',
       'public',
       '*.config.js',
       '*.config.mjs',
       '*.config.ts',
       '.kilo',
       '.kilo/**',
       '**/dist/**',
       'packages/rbac/deno/**',
     ]
  },
  {
    extends: [ js.configs.recommended, ...tseslint.configs.recommended ],
    files: [ '**/*.{ts,tsx}' ],
    languageOptions: {
      ecmaVersion: 2020,
      parserOptions: {
        project: [ './tsconfig.json', './tsconfig.api.json', './tsconfig.tests.json', './packages/rbac/tsconfig.json' ],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        location: 'readonly',
        history: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Worker: 'readonly',
        ServiceWorker: 'readonly',
        Notification: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Symbol: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        globalThis: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/refs': 'warn',

      // TypeScript strictness
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [ 'error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' } ],
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-misused-promises': 'warn',

      // Code quality
      'no-console': [ 'warn', { allow: [ 'error', 'warn', 'info' ] } ],
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': [ 'error', 'always' ],
      'no-duplicate-imports': 'error',
      'no-unused-expressions': 'warn',
      'curly': [ 'error', 'all' ],
      'no-implicit-coercion': 'warn',
      'no-eval': 'error',
      'no-new-func': 'error',
      'prefer-arrow-callback': 'warn',
      'arrow-body-style': [ 'warn', 'as-needed' ],
      'react-refresh/only-export-components': 'off',

      // Function complexity
      'complexity': [ 'warn', 20 ],
      'max-lines-per-function': [ 'warn', { max: 150, skipBlankLines: true, skipComments: true } ],
      'max-params': [ 'warn', 4 ],
      'max-depth': [ 'warn', 4 ],
      'max-nested-callbacks': 'off',
    },
  },
  {
    files: [ 'tests/**/*.ts', 'tests/**/*.tsx' ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'max-lines-per-function': 'off',
      'no-console': 'off',
    },
  },
);
