import { normalizeTextTree } from '../../utils/textEncoding';

const walletTextSource = {
  en: {
    walletTitle: 'Wasel Wallet',
    balance: 'Available Balance',
    pending: 'Pending',
    rewards: 'Rewards',
    hideBalance: 'Hide balance',
    showBalance: 'Show balance',
    addMoney: 'Add Money',
    withdraw: 'Withdraw',
    sendMoney: 'Send',
    overview: 'Overview',
    transactions: 'Transactions',
    send: 'Send',
    rewardsTab: 'Rewards',
    insights: 'Insights',
    settings: 'Settings',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    noTransactions: 'No transactions yet',
    quickActions: 'Core Actions',
    topUpAmount: 'Top-up Amount (JOD)',
    paymentMethod: 'Payment Method',
    card: 'Credit/Debit Card',
    applePay: 'Apple Pay',
    bankTransfer: 'Bank Transfer',
    cliq: 'CliQ',
    topUp: 'Top Up',
    withdrawAmount: 'Withdrawal Amount (JOD)',
    bankAccount: 'Bank Account / IBAN',
    instant: 'Instant',
    standard: 'Standard (1-3 days)',
    confirmWithdraw: 'Withdraw',
    recipientId: 'Recipient User ID',
    sendAmount: 'Amount (JOD)',
    noteOptional: 'Note (optional)',
    confirmSend: 'Send Money',
    activeRewards: 'Active Rewards',
    claimedRewards: 'Claimed Rewards',
    claim: 'Claim',
    expires: 'Expires',
    noRewards: 'No rewards available',
    spendingInsights: 'Spending Insights',
    thisMonth: 'This Month',
    vsLastMonth: 'vs last month',
    earned: 'Earned',
    spent: 'Spent',
    monthlyTrend: 'Monthly Trend',
    categoryBreakdown: 'Category Breakdown',
    securityPin: 'Wallet PIN',
    setPin: 'Set PIN',
    changePin: 'Change PIN',
    pinDescription: 'Protect transactions with a 4-digit PIN',
    autoTopUp: 'Auto Top-Up',
    autoTopUpDesc: 'Automatically add funds when balance drops below threshold',
    threshold: 'Threshold (JOD)',
    topUpAmountSetting: 'Top-up Amount (JOD)',
    subscription: 'Wasel Plus',
    subscribeNow: 'Subscribe Now',
    activeSubscription: 'Active Subscription',
    escrow: 'Active Escrows',
    held: 'Held',
    processing: 'Processing...',
    loadingTitle: 'Loading your wallet',
    loadingDescription: 'Loading wallet data.',
    pinDigits: 'Enter 4-digit PIN',
    carbonSaved: 'CO2 Saved',
    totalTx: 'Total Transactions',
    jod: 'JOD',
    liveStatus: 'Live',
    walletSubtitle: 'Balance and rewards',
    redirectingToSignIn: 'Redirecting to sign in...',
    walletUnavailableTitle: 'Wallet unavailable',
    walletUnavailableDescription: 'Complete wallet setup to unlock payments.',
    walletUnavailableHint: 'Setup still in progress',
    rewardsEmptyHint: 'Complete trips to earn rewards',
    availableLabel: 'Available',
    freeLabel: 'Free',
    userIdPlaceholder: 'User ID',
    notePlaceholder: 'Note...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'Active',
    invalidAmount: 'Enter a valid amount',
    enterBankAccount: 'Enter bank account',
    insufficientBalance: 'Insufficient balance',
    enterRecipientId: 'Enter recipient ID',
    pinMustBeFourDigits: 'PIN must be 4 digits',
    walletLoadError: 'Unable to load wallet right now',
    refreshed: 'Refreshed',
    refreshFailed: 'Refresh failed. Please try again.',
    refresh: 'Refresh',
    retry: 'Retry',
    insightsLoadError: 'Unable to load insights right now',
    paymentsEyebrow: 'Payments',
    heroDescription: 'Balance, transfers, and rewards in one clear surface.',
    autoTopUpOn: 'Auto top-up on',
    manualTopUp: 'Manual top-up',
    pendingSublabel: 'Funds waiting for settlement or withdrawal.',
    rewardsSublabel: 'Reward value available in the current cycle.',
    transactionsSublabel: 'Visible transaction count right now.',
    searchTransactions: 'Search transactions...',
    bookRideToEarnRewards: 'Book a ride to earn rewards',
    paymentCompleted: 'Payment completed. Wallet balance is refreshing.',
    paymentCancelled: 'Payment was cancelled before completion.',
    redirectingToPaymentCheckout: 'Redirecting to secure payment checkout',
    toppedUpSuccess: 'JOD {amount} added successfully',
    withdrawnSuccess: 'JOD {amount} withdrawn successfully',
    sentSuccess: 'JOD {amount} sent successfully',
    autoTopUpEnabledToast: 'Auto top-up enabled',
    autoTopUpDisabledToast: 'Auto top-up disabled',
    welcomeToPlus: 'Welcome to Wasel Plus!',
    redirectingToSubscriptionCheckout: 'Redirecting to secure subscription checkout',
    subscriptionCheckoutCompleted: 'Subscription checkout completed. Membership is refreshing.',
    subscriptionCheckoutCancelled: 'Subscription checkout was cancelled before completion.',
    rewardClaimed: 'Reward claimed!',
    pinSetSuccess: 'PIN set successfully',
    walletPinLabel: 'Wallet PIN',
    walletPinRequired: 'Enter your 4-digit wallet PIN to confirm',
    walletPinTooManyAttempts: 'Too many incorrect PIN attempts. Try again later.',
    topUpUnavailableHint: 'Secure wallet top-up is not configured in this environment yet.',
    subscriptionUnavailableHint:
      'Subscription checkout is disabled until wallet billing is configured.',
    rewardClaimUnavailableHint:
      'Rewards are visible, but claiming stays disabled until the wallet backend is configured.',
    pinUnavailableHint: 'PIN setup is disabled until the secure wallet backend is configured.',
  },
  ar: {
    topUpUnavailableHint: 'شحن المحفظة الآمن غير مفعّل في هذه البيئة بعد.',
    subscriptionUnavailableHint: 'الاشتراك معطّل حتى يكتمل إعداد فوترة المحفظة.',
    rewardClaimUnavailableHint: 'المكافآت مرئية، لكن استلامها معطّل حتى يكتمل إعداد خلفية المحفظة.',
    pinUnavailableHint: 'تعيين PIN معطّل حتى يكتمل إعداد خلفية المحفظة الآمنة.',
    walletTitle: 'محفظة واصل',
    balance: 'الرصيد المتاح',
    pending: 'معلق',
    rewards: 'المكافآت',
    hideBalance: 'إخفاء الرصيد',
    showBalance: 'إظهار الرصيد',
    addMoney: 'إضافة رصيد',
    withdraw: 'سحب',
    sendMoney: 'إرسال',
    overview: 'نظرة عامة',
    transactions: 'المعاملات',
    send: 'إرسال',
    rewardsTab: 'المكافآت',
    insights: 'التحليلات',
    settings: 'الإعدادات',
    recentTransactions: 'آخر المعاملات',
    viewAll: 'عرض الكل',
    noTransactions: 'ستظهر المعاملات هنا فور تفعيل المحفظة',
    quickActions: 'الإجراءات الأساسية',
    topUpAmount: 'مبلغ الشحن (دينار)',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة ائتمان أو خصم',
    applePay: 'أبل باي',
    bankTransfer: 'تحويل بنكي',
    cliq: 'كليك',
    topUp: 'شحن',
    withdrawAmount: 'مبلغ السحب (دينار)',
    bankAccount: 'الحساب البنكي / IBAN',
    instant: 'فوري',
    standard: 'عادي (1-3 أيام)',
    confirmWithdraw: 'سحب',
    recipientId: 'معرف المستلم',
    sendAmount: 'المبلغ (دينار)',
    noteOptional: 'ملاحظة (اختياري)',
    confirmSend: 'إرسال المال',
    activeRewards: 'المكافآت النشطة',
    claimedRewards: 'المكافآت المستلمة',
    claim: 'استلام',
    expires: 'ينتهي',
    noRewards: 'لا توجد مكافآت متاحة',
    spendingInsights: 'تحليلات الإنفاق',
    thisMonth: 'هذا الشهر',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    earned: 'المكتسب',
    spent: 'المنفق',
    monthlyTrend: 'الاتجاه الشهري',
    categoryBreakdown: 'التفصيل حسب الفئة',
    securityPin: 'رمز PIN للمحفظة',
    setPin: 'تعيين PIN',
    changePin: 'تغيير PIN',
    pinDescription: 'احم معاملاتك برمز من 4 أرقام',
    autoTopUp: 'شحن تلقائي',
    autoTopUpDesc: 'أضف رصيداً تلقائياً عندما ينخفض الرصيد عن الحد المحدد',
    threshold: 'الحد الأدنى (دينار)',
    topUpAmountSetting: 'مبلغ الشحن (دينار)',
    subscription: 'واصل بلس',
    subscribeNow: 'اشترك الآن',
    activeSubscription: 'اشتراك فعال',
    escrow: 'عمليات الضمان النشطة',
    held: 'محجوز',
    processing: 'جارٍ المعالجة...',
    loadingTitle: 'جارٍ تحميل المحفظة',
    loadingDescription: 'نجمع الرصيد والمكافآت وآخر النشاطات.',
    pinDigits: 'أدخل رمزاً من 4 أرقام',
    carbonSaved: 'انبعاثات CO2 التي تم توفيرها',
    totalTx: 'إجمالي المعاملات',
    jod: 'دينار',
    liveStatus: 'نشط',
    walletSubtitle: 'المدفوعات والرصيد والمكافآت',
    redirectingToSignIn: 'جارٍ تحويلك إلى تسجيل الدخول...',
    walletUnavailableTitle: 'المحفظة قيد الإطلاق',
    walletUnavailableDescription:
      'نجهز تدفق المدفوعات والأمان والتسوية. أكمل إعداد الخلفية لرؤية تجربة المحفظة الكاملة.',
    walletUnavailableHint: 'تجربة مالية أكثر تنسيقاً قريباً',
    rewardsEmptyHint: 'أكمل رحلات لتربح مكافآت',
    availableLabel: 'الرصيد المتاح',
    freeLabel: 'مجاني',
    userIdPlaceholder: 'معرف المستلم',
    notePlaceholder: 'ملاحظة...',
    maskedBalance: '******',
    maskedShort: '**',
    maskedPin: '****',
    activeLabel: 'نشط',
    invalidAmount: 'أدخل مبلغاً صحيحاً',
    enterBankAccount: 'أدخل رقم الحساب',
    insufficientBalance: 'الرصيد غير كافٍ',
    enterRecipientId: 'أدخل معرف المستلم',
    pinMustBeFourDigits: 'الرمز يجب أن يكون 4 أرقام',
    walletLoadError: 'تعذر تحميل المحفظة الآن',
    refreshed: 'تم التحديث',
    refreshFailed: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
    refresh: 'تحديث',
    retry: 'إعادة المحاولة',
    insightsLoadError: 'تعذر تحميل التحليلات الآن',
    paymentsEyebrow: 'المدفوعات',
    heroDescription: 'الرصيد والتحويلات والمكافآت في مكان واحد واضح.',
    autoTopUpOn: 'شحن تلقائي',
    manualTopUp: 'شحن يدوي',
    pendingSublabel: 'أموال بانتظار التسوية أو السحب.',
    rewardsSublabel: 'قيمة المكافآت المتاحة في الدورة الحالية.',
    transactionsSublabel: 'عدد المعاملات الظاهر حالياً.',
    searchTransactions: 'ابحث في المعاملات...',
    bookRideToEarnRewards: 'احجز رحلة لتربح مكافآت',
    paymentCompleted: 'اكتمل الدفع. جارٍ تحديث رصيد المحفظة.',
    paymentCancelled: 'تم إلغاء الدفع قبل الاكتمال.',
    redirectingToPaymentCheckout: 'جارٍ تحويلك إلى صفحة دفع آمنة',
    toppedUpSuccess: 'تمت إضافة {amount} دينار بنجاح',
    withdrawnSuccess: 'تم سحب {amount} دينار بنجاح',
    sentSuccess: 'تم إرسال {amount} دينار بنجاح',
    autoTopUpEnabledToast: 'تم تفعيل الشحن التلقائي',
    autoTopUpDisabledToast: 'تم إيقاف الشحن التلقائي',
    welcomeToPlus: 'مبروك! تم الاشتراك في واصل بلس',
    redirectingToSubscriptionCheckout: 'جارٍ تحويلك إلى صفحة اشتراك آمنة',
    subscriptionCheckoutCompleted: 'اكتمل دفع الاشتراك. جارٍ تحديث العضوية.',
    subscriptionCheckoutCancelled: 'تم إلغاء دفع الاشتراك قبل الاكتمال.',
    rewardClaimed: 'تم استلام المكافأة!',
    pinSetSuccess: 'تم تعيين PIN بنجاح',
    walletPinLabel: 'رمز المحفظة (PIN)',
    walletPinRequired: 'أدخل رمز المحفظة المكوّن من 4 أرقام للتأكيد',
    walletPinTooManyAttempts: 'محاولات خاطئة كثيرة للرمز. حاول مرة ثانية بعد شوي.',
  },
} as const;

export const walletText = normalizeTextTree(walletTextSource);
