/**
 * Wasel RBAC — Deno/Edge Function Entry Point
 *
 * This file is the Deno-compatible export of the canonical RBAC definitions.
 * It re-exports from the main source to ensure single source of truth.
 *
 * In CI/build, this file is generated by copying src/index.ts to deno/index.ts
 * with any Deno-specific adjustments (e.g., removing Node.js-only features).
 */
export { hasPermission, assertPermission, resolveAccessRole, userHasPermission, getRolePermissions, getRolesWithPermission, getAllRoles, getAllPermissions, isHighPrivilegeRole, canWritePayments, canManageUsers, } from '../src/index.ts';
// Deno-specific: Make ROLE_PERMISSIONS available for direct inspection
// (In Deno, we can't easily import the const from src without bundling)
export const ROLE_PERMISSIONS_DENO = {
    admin: [
        'rides:read', 'rides:write', 'rides:assign', 'rides:cancel_any', 'rides:price_override',
        'packages:read', 'packages:write', 'packages:assign', 'packages:cancel_any',
        'payments:read', 'payments:write', 'payments:refund', 'payments:payout', 'payments:reconcile',
        'operations:read', 'operations:write', 'fleet:manage', 'corridors:manage',
        'trust:read', 'trust:moderate', 'trust:ban', 'identity:review',
        'disputes:read', 'disputes:write', 'support:read', 'support:write',
        'users:read', 'users:write', 'users:impersonate',
        'notifications:read', 'notifications:send',
        'bus:read', 'bus:write', 'bus:manage_schedules',
        'corporate:read', 'corporate:write',
        'school:read', 'school:write',
        'medical:read', 'medical:write',
        'analytics:read', 'analytics:export',
        'events:publish', 'events:consume',
        'config:read', 'config:write',
    ],
    finance: [
        'payments:read', 'payments:write', 'payments:refund', 'payments:payout', 'payments:reconcile',
        'rides:read', 'packages:read', 'bus:read',
        'users:read',
        'analytics:read', 'analytics:export',
        'notifications:read',
        'config:read',
    ],
    trust: [
        'trust:read', 'trust:moderate', 'trust:ban', 'identity:review',
        'users:read', 'users:write',
        'rides:read', 'packages:read',
        'disputes:read', 'disputes:write',
        'support:read',
        'notifications:read', 'notifications:send',
        'analytics:read',
    ],
    support: [
        'rides:read', 'packages:read', 'bus:read',
        'payments:read',
        'disputes:read', 'disputes:write',
        'support:read', 'support:write',
        'users:read',
        'trust:read',
        'notifications:read',
    ],
    operator: [
        'rides:read', 'rides:assign',
        'packages:read', 'packages:assign',
        'payments:read',
        'operations:read', 'operations:write',
        'fleet:manage', 'corridors:manage',
        'trust:read', 'trust:moderate',
        'bus:read', 'bus:write',
        'notifications:read', 'notifications:send',
        'analytics:read',
    ],
    driver: [
        'rides:read', 'rides:write',
        'packages:read', 'packages:write',
        'payments:read',
        'notifications:read',
    ],
    user: [
        'rides:read', 'rides:write',
        'packages:read', 'packages:write',
        'payments:read',
        'bus:read',
        'notifications:read',
    ],
    corporate: [
        'rides:read', 'rides:write',
        'packages:read', 'packages:write',
        'payments:read',
        'bus:read',
        'corporate:read', 'corporate:write',
        'notifications:read',
        'analytics:read',
    ],
    school: [
        'rides:read', 'rides:write',
        'school:read', 'school:write',
        'payments:read',
        'notifications:read',
    ],
    medical: [
        'rides:read', 'rides:write',
        'medical:read', 'medical:write',
        'payments:read',
        'notifications:read',
    ],
    package_agent: [
        'packages:read', 'packages:write',
        'payments:read',
        'notifications:read',
    ],
    bus_operator: [
        'bus:read', 'bus:write', 'bus:manage_schedules',
        'rides:read',
        'payments:read',
        'operations:read',
        'notifications:read',
    ],
    guest: [
        'rides:read',
        'bus:read',
        'config:read',
    ],
    service: [
        'events:publish', 'events:consume',
        'rides:read', 'packages:read',
        'payments:read',
        'notifications:send',
        'config:read',
    ],
};
export const VALID_ROLES_DENO = [
    'admin', 'finance', 'trust', 'support', 'operator', 'driver', 'user',
    'corporate', 'school', 'medical', 'package_agent', 'bus_operator', 'guest', 'service',
];
