/**
 * Wasel RBAC — Deno/Edge Function Entry Point
 *
 * This file is the Deno-compatible export of the canonical RBAC definitions.
 * It re-exports from the main source to ensure single source of truth.
 *
 * In CI/build, this file is generated by copying src/index.ts to deno/index.ts
 * with any Deno-specific adjustments (e.g., removing Node.js-only features).
 */
export type { AccessRole, AccessPermission, } from '../src/index.ts';
export { hasPermission, assertPermission, resolveAccessRole, userHasPermission, getRolePermissions, getRolesWithPermission, getAllRoles, getAllPermissions, isHighPrivilegeRole, canWritePayments, canManageUsers, } from '../src/index.ts';
export declare const ROLE_PERMISSIONS_DENO: Record<string, readonly string[]>;
export declare const VALID_ROLES_DENO: readonly ["admin", "finance", "trust", "support", "operator", "driver", "user", "corporate", "school", "medical", "package_agent", "bus_operator", "guest", "service"];
//# sourceMappingURL=index.d.ts.map